- name: install and run nginix
  hosts: web
  become: yes # -b given sudo accesss
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start the nginx
      ansible.builtin.service:
        name: nginix
        state: started    