- name: variables
  hosts: local
  connection: local
  vars: #play level variables are global variables
   COURSE: "DevOps with AWS"
   DURATION: 120HRS
   TRAINER: SHIVA KUMAR
   tasks: 
     - name: print the variable
       vars: #task level variables can override play level variables also called local variables
        COURSE: ansible
       ansible.builtin.debug:
        msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
     
     - name: print the variables1
       ansible.builtin.debug:
         msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}" 
