- name: install nginx
  hosts: web
  become: yes
  tasks:
   - name: install nginx of RHEL
     ansible.builtin.dnf:
      name: nginx
      state: installed
     when: ansible_os_family == "RedHat"  

   - name: install nginx of ubuntu
     ansible.builtin.apt:
      name: nginx
      state: installed
     when: ansible_os_family == "Debian"    
