- name: loops
  hosts: local
  connection: local 
  tasks:
   - name: print name
      ansible.builtin.debug:
       msg: "hello {{ item }}"
      loop:
      - jung kook
      - tae
      - j hope 
     #item is a reserved key word