- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange" #String
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"


  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: conver list into map
    vars:
     course:
     - {'key': 'name', 'value': 'ansible'} 
     - {'key': 'duration', 'value': '10hrs'}
     - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
     msg: "course info: {{ course | items2dict }}"


  - name: convert lower to upper
    tags:
    - uppertolower
    vars:
      name: "shiva kumar reddy M"   
    ansible.builtin.debug:
       msg: "Hello {{ name | upper }}"


  - name: convert upper to lower
    vars:
      name: "SHIVA KUMAR REDDY  M"   
    ansible.builtin.debug:
       msg: "Hello {{ name | lower }}"

  - name: print min and max 
    vars:
     numbers: [10,25,32,55,82,2,69,158,2655]
    ansible.builtin.debug:
     msg: "min is: {{ numbers | min }} max is: {{numbers | max}}"    

  - name: check ip adress is valid or not
    vars:
     ip: "192.168.1.1"  #have to give valid ip
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"   